version: '3'

services:

    rabbit:
        image: rabbitmq:3.6.11
        restart: always
        hostname: rabbit
        environment:
            - RABBITMQ_DEFAULT_USER=wiki
            - RABBITMQ_DEFAULT_PASS=wiki123
        ports:
            - "5673:5672"
        networks:
          - wiki_network
        volumes:
          - 'wiki_rabbit:/data'

    # mongo:
    #     build: ./environments/light/mongo
    #     restart: always
    #     environment:
    #         MONGO_ROLE: primary
    #         MONGO_ROOT_USER: wikiadmin
    #         MONGO_ROOT_PASSWORD: wikiadmin123
    #         MONGO_APP_USER: wiki
    #         MONGO_APP_PASSWORD: wiki123
    #         MONGO_APP_DATABASE: wiki_history_extractor
    #     tty: true
    #     hostname: mongo
    #     stdin_open: true
    #     networks:
    #         - wiki_network

    nginx:
        image: nginx:1.13.3
        restart: always
        links:
            - flask
        ports:
            - "80:80"
        networks:
          - wiki_network
        volumes:
            - './environments/light/nginx/nginx.conf:/etc/nginx/nginx.conf:ro'
        depends_on:
            - flask
            
    flask:
        build: .
        restart: always
        environment:
            - FLASK_CONFIG=digital_ocean
            - PYTHONBUFFERED=true
            - FLASK_DEBUG=1
            - MONGO_HOST=ds123124.mlab.com
            - MONGO_PORT=23124
            - MONGO_USERNAME=wiki
            - MONGO_PASSWORD=wiki123
        links:
            - rabbit
        ports:
            - '80'
        networks:
          - wiki_network
        volumes:
          - '.:/app'
        depends_on:
            - rabbit
    
    worker:
        build: .
        restart: always
        command: celery worker -A celery_worker.celery --loglevel=info
        environment:
            - FLASK_CONFIG=digital_ocean
            - PYTHONBUFFERED=true
            - FLASK_DEBUG=1
            - MONGO_HOST=ds123124.mlab.com
            - MONGO_PORT=23124
            - MONGO_USERNAME=wiki
            - MONGO_PASSWORD=wiki123
        links:
            - rabbit
        networks:
          - wiki_network
        volumes:
          - '.:/app'
        depends_on:
            - rabbit

volumes:
    wiki_rabbit:

networks:
  wiki_network:
