version: '3'

services:

    rabbit:
        image: rabbitmq:3.6.11
        restart: always
        hostname: rabbit
        environment:
            - RABBITMQ_DEFAULT_USER=wiki
            - RABBITMQ_DEFAULT_PASS=wiki123
        ports:
            - "5673:5672"
        networks:
          - wiki_network
        volumes:
          - 'wiki_rabbit:/data'

    mongo:
        image: mongo:3.6.2
        restart: always
        hostname: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=wiki
            - MONGO_INITDB_ROOT_PASSWORD=wiki123
        ports:
            - 27018:27017
        networks:
            - wiki_network
        volumes:
            - 'wiki_mongo:/data/db'

    nginx:
        build: ./docker/nginx
        image: nginx:1.13.3
        restart: always
        links:
            - flask
            - flower:flower
            - events:events
        ports:
            - "80:80"
        networks:
          - wiki_network
        volumes:
            - './environments/light/nginx/nginx.conf:/etc/nginx/nginx.conf:ro'
        depends_on:
            - flask
            
    flask:
        build: .
        image: wheapi
        restart: always
        environment:
            - FLASK_CONFIG=docker
            - PYTHONBUFFERED=true
            - FLASK_DEBUG=1
        command: python manage.py runserver --host 0.0.0.0 --port=3031
        #command: /usr/local/bin/uwsgi --socket 0.0.0.0:3031 --uid uwsgi --protocol uwsgi --wsgi manage:app --py-autoreload 1
        #command: /usr/local/bin/uwsgi --socket 0.0.0.0:3031 --uid uwsgi --protocol http --wsgi manage:app --py-autoreload 1
        links:
            - rabbit
            - mongo:mongo
        ports:
            - "3031:3031"
        networks:
          - wiki_network
        volumes:
          - '.:/app'
        depends_on:
            - rabbit
            - mongo
    
    worker:
        build: .
        restart: always
        command: celery worker -A celery_worker.celery --loglevel=info
        environment:
            - FLASK_CONFIG=docker
            - PYTHONBUFFERED=true
            - FLASK_DEBUG=1
        links:
            - rabbit
            - mongo:mongo
        networks:
          - wiki_network
        depends_on:
            - rabbit
            - mongo
    
    flower:
        build: .
        restart: always
        command: celery flower -A celery_worker.celery --loglevel=info
        links:
            - rabbit
            - mongo:mongo
        networks:
          - wiki_network
        depends_on:
            - rabbit
            - mongo
    
    events:
        build: .
        restart: always
        command: celery events -A celery_worker.celery --loglevel=info
        links:
            - rabbit
            - mongo:mongo
        networks:
          - wiki_network
        depends_on:
            - rabbit
            - mongo

volumes:
    wiki_rabbit:
    wiki_mongo:

networks:
  wiki_network:
